# Generated by Django 5.0.3 on 2024-03-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(default='dd673e2c723f402d8c6f1c5c21481603', max_length=32, unique=True)),
                ('foreground', models.CharField(default='000000', max_length=6)),
                ('background', models.CharField(default='FFFFFF', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datetime', models.DateField()),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('time_zone', models.CharField(default='Europe/Moscow', max_length=255)),
                ('user_name', models.CharField(max_length=12)),
                ('biography', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default='d752aa7544b94ac69535da12e3ed4b34', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'confirmed'), ('tentative', 'tentative'), ('canceled', 'canceled')], default='tentative', max_length=9)),
                ('html_link', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=models.DateTimeField(auto_now_add=True))),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(default=None)),
                ('event_type', models.CharField(choices=[('default', 'default'), ('outOfOffice', 'outOfOffice'), ('workingLocation', 'workingLocation')], default='default', max_length=15)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.color', to_field='color_id')),
                ('end', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='event_end', to='personalapp.eventdate')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_start', to='personalapp.eventdate')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to='personalapp.user')),
                ('organizer', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to='personalapp.user'), on_delete=django.db.models.deletion.SET, related_name='event_organizer', to='personalapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=12)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('organizer', models.BooleanField(default=False)),
                ('response_status', models.CharField(choices=[('needsAction', 'needsAction'), ('declined', 'declined'), ('tentative', 'tentative'), ('accepted', 'accepted')], default='needsAction', max_length=11)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.event', to_field='event_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('title', models.CharField(max_length=25)),
                ('mime_type', models.TextField(default=None)),
                ('icon_link', models.TextField(default=None)),
                ('file_id', models.TextField(default=None)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.event', to_field='event_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.CharField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('yearly', 'YEARLY')], max_length=7)),
                ('interval', models.IntegerField(default=0)),
                ('by_month', models.CharField(default='', max_length=24)),
                ('by_day', models.CharField(default='', max_length=7)),
                ('until', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.event', to_field='event_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateTimeField(default=None)),
                ('d_start', models.DateTimeField(default=None)),
                ('r_date', models.DateTimeField(default=None)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.event', to_field='event_id')),
                ('r_rule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personalapp.recurrencerule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('task', models.CharField(max_length=255)),
                ('description', models.TextField(default=None)),
                ('status', models.CharField(choices=[('onTrack', 'On Track'), ('onHold', 'On Hold'), ('done', 'Done'), ('ready', 'Ready'), ('offTrack', 'Off Track'), ('blocked', 'Blocked')], default='onTrack', max_length=8)),
                ('link', models.CharField(default=None, max_length=255)),
                ('role', models.CharField(choices=[('contributor', 'contributor'), ('executor', 'executor'), ('customer', 'customer'), ('sponsor', 'sponsor')], default='contributor', max_length=11)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(default=None)),
                ('link', models.CharField(default=None, max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalapp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
