# Generated by Django 5.0.3 on 2024-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0002_user_spec_alter_color_color_id_alter_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.CharField(default='4993cbe31bfd4ab1b631531dd2229001', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='ce5f2ecd3ebc4483a5cdfc54735962d0', max_length=32, unique=True),
        ),
    ]
