# Generated by Django 5.0.3 on 2024-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spec',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_id',
            field=models.CharField(default='1871c6fd57744b17be52f651629528f3', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='7eba0e6f4a1740778ed55844b8e5a052', max_length=32, unique=True),
        ),
    ]
